[build]
  builder = "nixpacks"
  buildCommand = "npm run build"

[deploy]
  startCommand = "npm run preview"
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartPolicyType = "on-failure"
  restartPolicyMaxRetries = 10

[deploy.envs]
  PORT = "3000"
  NODE_ENV = "production"